name: Repo Dispatcher

on:
  schedule:
    - cron: 35 18 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install aggregate whois jq unzip p7zip-full

    - name: Update IP List
      env:
        URL: ${{secrets.URL}}
      run: |
        chmod +x update
        ./update

    - name: Delete workflow runs
      uses: small-5/delete-workflow-runs@main
      with:
        retain_min: 0
        keep_minimum_runs: 0
